swagger: "2.0"
info:
  description: "Projeto Integado do 2º semestre do curso Técnico em Desenvolvimento de Sistemas. Este projeto permitirá aos alunos realizar a integração das unidades curriculares de Banco de Dados, Programação Web Front-End, Programação Web Back-End e Programação de Dispositivos Móveis. Professores envolvidos (Celso, Fernando e Marcel)"
  version: "1.0.0"
  title: "Projeto Integrado - Pizzaria"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Senai Jandira"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "Pizzaria"
  description: "Operações para Pizzaria"
schemes:
- "http"
paths:
  /v1/usuario:
    post:
      tags:
      - "usuario"
      summary: "Inserir novo Usuário"
      description: "Para inserir o novo usuário é necessário estar autenticado no sistema, esse usuário irá administrar o Dashboard do sistema"
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Novo Usuário"
        required: true
        schema:
          $ref: "#/definitions/Usuario"
      responses:
        "201":
          description: "Item criado com sucesso"
    get:
      tags:
      - "usuario"
      summary: "Listar todos os usuários"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/ListUsuarios"
        "404":
          description: "Item não encontrado"
  /v1/usuario/{id}:
    get:
      tags:
      - "usuario"
      summary: "Buscar um usuário"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/NivelUsuarios"
        "404":
          description: "Item não encontrado"        
    put:
      tags:
      - "usuario"
      summary: "Atualizar Usuário"
      description: "Para atualizar o usuário é necessário estar autenticado no sistema, e deverá ser enviado o ID"
      operationId: "Atualizar Usuário"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      
      - in: "body"
        name: "body"
        description: "Atualizar Usuário"
        required: true
        schema:
            $ref: "#/definitions/Usuario"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
    delete:
      tags:
      - "usuario"
      summary: "Excluir Usuário"
      description: "Para excluir o usuário é necessário estar autenticado no sistema, e deverá ser enviado o ID"
      operationId: "Excluir Usuário"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
        "400":
          description: "Item não encontrado"  
          
  /v1/nivel:
    get:
      tags:
      - "nivel-usuario"
      summary: "Listar todos os níveis de usuários"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/NivelUsuarios"
        "404":
          description: "Item não encontrado"        
  /v1/nivel/{id}:
    get:
      tags:
      - "nivel-usuario"
      summary: "Buscar um nível de usuário"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/NivelUsuarios"
        "404":
          description: "Item não encontrado"                
          
  /v1/categoria:
    post:
      tags:
      - "categoria"
      summary: "Inserir nova categoria"
      description: "Para inserir a nova categoria é necessário estar autenticado no sistema, essa categoria será associada aos produtos no Dashboard do sistema"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Nova Categoria"
        required: true
        schema:
          $ref: "#/definitions/Categoria"
      responses:
        "201":
          description: "Item criado com sucesso"
    get:
      tags:
      - "categoria"
      summary: "Listar todas as categorias"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/Categoria"
        "404":
          description: "Item não encontrado"
  /v1/categoria/{id}:
    get:
      tags:
      - "categoria"
      summary: "Buscar uma categoria"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/NivelUsuarios"
        "404":
          description: "Item não encontrado"          
    put:
      tags:
      - "categoria"
      summary: "Atualizar Categoria"
      description: "Para atualizar a categoria é necessário estar autenticado no sistema, e deverá ser enviado o ID"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Atualizar Categoria"
        required: true
        schema:
            $ref: "#/definitions/Categoria"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
    delete:
      tags:
      - "categoria"
      summary: "Excluir Categoria"
      description: "Para excluir a categora é necessário estar autenticado no sistema, e deverá ser enviado o ID"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
        "400":
          description: "Item não encontrado"          
          
  /v1/produto:
    post:
      tags:
      - "produto"
      summary: "Inserir novo produto"
      description: "Para inserir um novo produto é necessário estar autenticado no sistema, esse produto será associada as categorias no Dashboard do sistema"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Nova Categoria"
        required: true
        schema:
          $ref: "#/definitions/Produto"
      responses:
        "201":
          description: "Item criado com sucesso"
    get:
      tags:
      - "produto"
      summary: "Listar todos os produtos"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/Produto"
        "404":
          description: "Item não encontrado"
  /v1/produto/{id}:
    get:
      tags:
      - "produto"
      summary: "Buscar um produto"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/Produto"
        "404":
          description: "Item não encontrado"          
    put:
      tags:
      - "produto"
      summary: "Atualizar Categoria"
      description: "Para atualizar o produto é necessário estar autenticado no sistema, e deverá ser enviado o ID"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
        
      - in: "body"
        name: "body"
        description: "Atualizar Produto"
        required: true
        schema:
            $ref: "#/definitions/Produto"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
    delete:
      tags:
      - "produto"
      summary: "Excluir Produto"
      description: "Para excluir o produto é necessário estar autenticado no sistema, e deverá ser enviado o ID"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
        "400":
          description: "Item não encontrado"          
          
  /v1/cliente:
    post:
      tags:
      - "cliente"
      summary: "Inserir novo cliente"
      description: "Para inserir um novo cliente é necessário se cadastrar de forma básica (nome, login e senha) e depois atualizar os dados quando estiver autenticado no sistema"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Novo Cliente"
        required: true
        schema:
          $ref: "#/definitions/NovoCliente"
      responses:
        "201":
          description: "Item criado com sucesso"
    get:
      tags:
      - "cliente"
      summary: "Listar todos os clientes"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/Cliente"
        "404":
          description: "Item não encontrado"
  /v1/cliente/{id}:
    get:
      tags:
      - "cliente"
      summary: "Buscar um cliente"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/Cliente"
        "404":
          description: "Item não encontrado"          
    put:
      tags:
      - "cliente"
      summary: "Atualizar Cliente"
      description: "Para atualizar um cliente é necessário estar autenticado no sistema, e deverá ser enviado o ID"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      
      - in: "body"
        name: "body"
        description: "Novo Cliente"
        required: true
        schema:
            $ref: "#/definitions/Cliente"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
    delete:
      tags:
      - "cliente"
      summary: "Excluir Cliente"
      description: "Para excluir o cliente é necessário estar autenticado no sistema, e deverá ser enviado o ID do cliente e do produto"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item(s0 Encontrados"
          schema:
            $ref: "#/definitions/Favorito"
        "400":
          description: "Item não encontrado"          
          
  /v1/favorito/cliente/{idCliente}/produto/{idProduto}:
    post:
      tags:
      - "favorito"
      summary: "Inserir novo favorito"
      description: "Para inserir um novo cliente é necessário se cadastrar de forma básica (nome, login e senha) e depois atualizar os dados quando estiver autenticado no sistema"
      produces:
      - "application/json"
      parameters:
      - name: "idCliente"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
        
      - name: "idProduto"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"

      responses:
        "201":
          description: "Item criado com sucesso"
    delete:
      tags:
      - "favorito"
      summary: "Excluir Favorito"
      description: "Para excluir o Favorito é necessário estar autenticado no sistema, e deverá ser enviado o ID do cliente e do produto"
      parameters:
      - name: "idCliente"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
        
      - name: "idProduto"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
        "400":
          description: "Item não encontrado"          
  /v1/favorito/cliente/{idCliente}:
     get:
      tags:
      - "favorito"
      summary: "Listar Favoritos"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "idCliente"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/Favorito"
        "404":
          description: "Item não encontrado"  
        
  /v1/comentario/produto/{idProduto}/cliente/{idCliente}:
    post:
      tags:
      - "comentario"
      summary: "Inserir novo comentário"
      description: "Para inserir um comentário, deverá estar autenticado no mobile."
      produces:
      - "application/json"
      parameters:
      - name: "idProduto"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
        
      - name: "idCliente"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
        
      - in: "body"
        name: "body"
        description: "Novo Comentário"
        required: true
        schema:
          $ref: "#/definitions/Comentario"

      responses:
        "201":
          description: "Item criado com sucesso"
    delete:
      tags:
      - "comentario"
      summary: "Excluir Comentário"
      description: "Para excluir um comentário, deverá estar autenticado no mobile."
      parameters:
      - name: "idCliente"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
        
      - name: "idProduto"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item Atualizado com sucesso"
        "400":
          description: "Item não encontrado"          
  /v1/comentario/produto/{idProduto}:
     get:
      tags:
      - "comentario"
      summary: "Listar Comentários"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "idProduto"
        in: "path"
        description: "ID do registro é obrigatório"
        required: true
        type: "integer"
      responses:
        "200":
          description: "Item(s) encontrados"
          schema:
            $ref: "#/definitions/Comentario"
        "404":
          description: "Item não encontrado"            

definitions:
  Usuario:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      login:
        type: "string"
      senha:
        type: "string"
      idNivelUsuario:
        type: "integer"
  ListUsuarios:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      login:
        type: "string"
      senha:
        type: "string"
      nivelUsuario:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          nivel:
            type: "string"
  NivelUsuarios:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nivel:
        type: "string"
  Categoria:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      icone:
        type: "string"    
  Produto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      descricao:
        type: "string"
      preco:
        type: "number"
      percentualDesconto:
        type: "number"  
      fotoCapa:
        type: "string"
      destaque:
        type: "boolean"
      fotos:
        type: "array"
        items:
         $ref: "#/definitions/ProdutoFotos"
  ProdutoFotos:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      foto:
        type: "string"
  Cliente:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nome:
        type: "string"
      email:
        type: "string"
      celular:
        type: "string"
      cep:
        type: "string" 
      logradouro:
        type: "string" 
      bairro:
        type: "string"   
      uf:
        type: "string" 
      complemento:
        type: "string" 
      foto:
        type: "string"
  NovoCliente:
    type: "object"
    properties:
      nome:
        type: "string"
      login:
        type: "string"
      senha:
        type: "string"
  Favorito:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      idCliente:
        type: "integer"
        format: "int64"
      produtos:
        type: array
        items:
          $ref: "#/definitions/Produto"
  Comentario:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      titulo:
        type: "string"
      comentario:
        type: "string"
      nota:
        type: "number"
      data:
        type: "string"
      clientes:
        type: array
        items:
          $ref: "#/definitions/Cliente"          
  